### ISSUE TITLE
Crashes every time 

### ISSUE THREAD

**Issue by Unusual-Danger** [ComputerElite/play3rdper#1]
Whenever I try to play a song the game crashes. I have already tried disabling replay and a few other mods.

**Comment by ComputerElite** [comment]
I have tested it and experienced crashes after you **ended** a song. But those have been fixed and seemed to come from a scene transition which took too long. Anyone with similar experiences and a crash log is appreciated

**Comment by Unusual-Danger** [comment]
I just tried doing a full Beat Saber and Bmbf restart by uninstalling and reinstalling along with reloading the assets. Still crashes without any other mod on

**Comment by ComputerElite** [comment]
this is weird could you get a log?

Copy pasta from BSMG macros:
How to get a log on the Quest

1) Copy and paste the following into your file browser's address bar:
%appdata%\SideQuest\platform-tools
Make sure that you have a file named adb or adb.exe
2) Hold shift, and while holding, right click somewhere blank in that folder
3) Click 'Open command prompt' or 'Open PowerShell' 
4) Connect your Quest to your computer
5) Write .\adb.exe logcat > logcat.log in that command line window that was opened and press enter 
Leave that window opened, and start the game on the Quest (while it is connected to your PC)
6) Then, play/fail a song, or any other thing that you need to get a log for, and take off your Quest
7) You can now close the command line window that you opened before
8) A file named logcat.log will be in the folder you opened first
9) Drag and drop that file into Discord to upload the log file

**Comment by ComputerElite** [comment]
Log was sent via Discord. Issue is the disable while replaying function which I'll now disable until full Replay is out. Thanks for your time and bug report
